// <auto-generated />
using System;
using CarPark.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPark.Api.Data.Migrations
{
    [DbContext(typeof(CarParkDbContext))]
    partial class CarParkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPark.Api.Data.Models.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeIn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("TimeOut")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("VehicleCharge")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpaceNumber");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("CarPark.Api.Data.Models.ParkingSpace", b =>
                {
                    b.Property<int>("SpaceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpaceNumber"));

                    b.HasKey("SpaceNumber");

                    b.ToTable("ParkingSpaces");

                    b.HasData(
                        new
                        {
                            SpaceNumber = 1
                        },
                        new
                        {
                            SpaceNumber = 2
                        },
                        new
                        {
                            SpaceNumber = 3
                        },
                        new
                        {
                            SpaceNumber = 4
                        },
                        new
                        {
                            SpaceNumber = 5
                        },
                        new
                        {
                            SpaceNumber = 6
                        },
                        new
                        {
                            SpaceNumber = 7
                        },
                        new
                        {
                            SpaceNumber = 8
                        },
                        new
                        {
                            SpaceNumber = 9
                        },
                        new
                        {
                            SpaceNumber = 10
                        });
                });

            modelBuilder.Entity("CarPark.Api.Data.Models.ParkingSession", b =>
                {
                    b.HasOne("CarPark.Api.Data.Models.ParkingSpace", null)
                        .WithMany("ParkingSessions")
                        .HasForeignKey("SpaceNumber")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CarPark.Api.Data.Models.ParkingSpace", b =>
                {
                    b.Navigation("ParkingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
